# Generated by Django 2.0.1 on 2018-02-04 00:24

from django.db import migrations
from django.contrib.auth.models import User
from account.models import Profile


def initalize_profiles(apps, schema_editor):

    for user in User.objects.all():
        Profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initalize_profiles),
    ]
